[theme]
name = "plain"

[icons]
name = "material-nf"

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
on_click = "xkb-switch -n"
format = "{layout}"
interval = 1

[[block]]
block = "time"
interval = 1
format = "%R"

[[block]]
block = "time"
interval = 1
[block.format]
full = "%a %d.%m.%y"
short = "%d.%m"
[block.icons_overrides]
time = ""

[[block]]
block = "sound"
show_volume_when_muted = true
headphones_indicator = true

[[block]]
block = "sound"
device_kind = "source"
show_volume_when_muted = true

[[block]]
block = "cpu"
info = 50
warning = 50
critical = 90
interval = 1
[block.format]
full = "{utilization} {barchart}"
short = "{utilization}"

[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
clickable = false
warning_mem = 67
critical_mem = 95
interval = 1

[[block]]
block = "net"
format = "{ssid} {speed_down;K*b} {speed_up;K*b}"
interval = 1

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT*"
hide_missing = true
interval = 1
