[theme]
name = "native"
[theme.overrides]
info_fg = "#44D0FE"
good_fg = "#4DA241"
warning_fg = "#FCD63B"
critical_fg = "#E9672D"

[icons]
name = "material-nf"

[[block]]
block = "music"
max_width = 30
[block.format]
full = "{combo}"
short = ""

[[block]]
block = "cpu"
info = 50
warning = 50
critical = 90
interval = 1
[block.format]
full = "{utilization} {barchart}"
short = "{utilization}"

[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
clickable = false
warning_mem = 67
critical_mem = 95
interval = 1

[[block]]
block = "disk_space"
path = "/home"
format = "{icon} {percentage}"
info_type = "used"
warning = 80
alert = 95

[[block]]
block = "net"
format = "{ssid} {speed_down;K*b} {speed_up;K*b}"
interval = 1

[[block]]
block = "sound"
show_volume_when_muted = true
headphones_indicator = true

[[block]]
block = "sound"
device_kind = "source"
show_volume_when_muted = true

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
on_click = "xkb-switch -n"
format = "{layout}"
interval = 1

[[block]]
block = "time"
format = " %a %d.%m.%y  %R"
interval = 1
[block.format]
full = " %a %d.%m.%y  %R"
short = " %d.%m  %R"
[block.icons_overrides]
time = ""
