[theme]
theme = "plain"

[icons]
icons = "material-nf"

[[block]]
block = "custom"
command = "xkb-switch -p"
interval = 1
[[block.click]]
button = "left"
cmd = "xkb-switch -n"
update = true

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%R') "

[[block]]
block = "time"
interval = 1
[block.format]
full = " $timestamp.datetime(f:'%a %d.%m.%y') "
short = " $timestamp.datetime(f:'%d.%m') "

[[block]]
block = "sound"
show_volume_when_muted = true
headphones_indicator = true

[[block]]
block = "sound"
device_kind = "source"
show_volume_when_muted = true

[[block]]
block = "cpu"
interval = 1
[block.format]
full = " $utilization $barchart "
short = " $utilization "

[[block]]
block = "memory"
warning_mem = 67
critical_mem = 95
interval = 1
format = " $mem_used/$mem_total ($mem_used_percents) "

[[block]]
block = "net"
format = " {^icon_net_wireless $ssid |}$speed_down.eng(prefix:K) ^icon_net_down $speed_up.eng(prefix:K) ^icon_net_up "
missing_format = ""
interval = 1

[[block]]
block = "battery"
device = "BAT"
interval = 1
missing_format = ""
